### ISSUE TITLE
[Feature] Fallback route when none match

### ISSUE THREAD

**Issue by ashleysommer** [sanic-org/sanic-routing#63]
I'm working on an app that has a pretty unique routing requirement.

I need something that looks like this:

```python
app = Sanic()

@app.get("/login")
async def login(request):
    ...

@app.get("/logout")
async def logout(request):
    ...

@app.get("/metrics")
async def metrics(request):
    ...

@app.route("/<mypath:path>")
async def fallback(request, mypath: str):
    # all other routes go to this handler
    ...
```

Implementing it as-is does not work because the "/\<mypath:path\>" matches _all_ routes and overrides the other route handlers.

One thought would be to have the ability to assign a priority weight on the route, like:
```python
@app.get("/login", priority=1)
async def login(request):
    ...

@app.route("/<mypath:path>", priority=9)
async def fallback(request, mypath: str):
    # this handler is evaluated after those with higher priority (lower number)
    ...
```

That might break some backwards compatibility (not sure), another solution would be to have a new match type, that is always evaluated last in the router (and this kind would never return a NotFound from the router).
```python
@app.route("/<mypath:fallback>")
async def fallback(request, mypath: str):
    # this handler is evaluated after those with higher priority (lower number)
    ...
```

Does that seem useful? Or have I missed an obvious way to achieve this?

**Comment by ashleysommer** [comment]
Ok, I don't know what I was doing wrong earlier, but I cannot reproduce my issue now.

Now the \<path\> route always matches last, which is what I wanted.

Note, I also tried it with a regex, like `@app.route(r"/<mypath:(.*)>")` and that worked fine too (I think regexes are checked after all other route types).

**Comment by ahopkins** [comment]
Yes, there are actually two different sets of priority for regex routes. "Standard" regex that does not include anything that could potentially match on multiple segments are evaluated inline in the order they would otherwise match. In general, that means most deeply nested first, but it also depends upon the priority of the path parameter type (since, for example a string type could match on both character and numbers).

The exception to the inline matching is when there is a `path` type or a regex with a `/`. These are always evaluated last so as to not clobber.

Not sure why you initially experienced an issue since a `<path:path>` is meant for that purpose and would always be at the end. That makes sense.
